### ISSUE TITLE
Update homepage link on NPM

### ISSUE THREAD

**Issue by robsonsobral** [vanilla-masker/vanilla-masker#107]
Hi!

The [homepage link on NPM](https://www.npmjs.com/package/vanilla-masker) points to [http://bankfacil.github.io/vanilla-masker]().

**Comment by fernandofleury** [comment]
Yeah, we need to update the links. You can send a PR or I'll work on it as soon as I can.

**Comment by leandrogrillo** [comment]
PR #125 fix old links
