### ISSUE TITLE
Demo page is down / URI Incorrect

### ISSUE THREAD

**Issue by netpoetica** [vanilla-masker/vanilla-masker#109]
There is a 404 for http://creditas.github.io/vanilla-masker/demo.html - the link provided from the [home page](https://fleury.io/vanilla-masker/).

The correct URI is https://fleury.io/vanilla-masker/demo.html

Maybe a quick run-through the page and make all URIs root-relative?

**Comment by iCaio** [comment]
Fixed here https://github.com/fernandofleury/vanilla-masker/commit/29db9ea71ae6b9dd656bdf4406e05d5cb8ed0fa1

**Comment by darlanmendonca** [comment]
continues down :(

**Comment by QuentinFchx** [comment]
Yeah, there have been lots of ownership transfers recently ^^
I just went back from holidays, I already merged some PRs fixing it.
Closing for now :)

**Comment by darlanmendonca** [comment]
what PR? just to subscribe and follow

**Comment by QuentinFchx** [comment]
https://github.com/vanilla-masker/vanilla-masker/pull/116
https://github.com/vanilla-masker/vanilla-masker/pull/117
or am I missing something?

**Comment by darlanmendonca** [comment]
so, write here when url is available, pls

**Comment by QuentinFchx** [comment]
Well it **is** already available. The PR were merged already and links _should be_ fixed.
https://vanilla-masker.github.io/vanilla-masker/

**Comment by darlanmendonca** [comment]
nice!!
