### ISSUE TITLE
Destroy/Unmask function

### ISSUE THREAD

**Issue by ImBobby** [vanilla-masker/vanilla-masker#11]
Hi, adding destroy or unmask function will be really helpful.

**Comment by fjsj** [comment]
I need this feature in Meteor, but it looks like AtmosphereJS version is 1.0.2: https://atmospherejs.com/bankfacil/vanilla-masker

Could you please update it?

**Comment by caio-ribeiro-pereira** [comment]
hi @fjsj what is your current meteor version?

**Comment by fjsj** [comment]
@caio-ribeiro-pereira it is Meteor 1.1.0.2

**Comment by caio-ribeiro-pereira** [comment]
@fjsj I'm using the same meteor version, I'll test soon to see what is happening, but if you can make a pull request too and @leandroadacosta will update quickly for you (because he is the only who have Meteor BankFacil accounts)
