### ISSUE TITLE
I wanted use the masker with react

### ISSUE THREAD

**Issue by LucasBadico** [vanilla-masker/vanilla-masker#121]
But, using ref isn\`t working properly. So I\`m think on use something like this:
```js
VMasker.toPattern(1099911111, "(99) 9999-9999") // in the same way that I set a value e return a masked value
// => (10) 9991-1111

VMasker.unMask("(01) 1111-1919", "(99) 9999-9999") // has a way to do that?
// => 011111919
```

Thanks!

**Comment by fernandofleury** [comment]
Why isn't it working properly with the ref?

**Comment by LucasBadico** [comment]
I`m working with a functional aprouch and just function components. Maybe because this is not working.

**Comment by fernandofleury** [comment]
can you show a code sample?

**Comment by dmscn-six** [comment]
Is this feature already implemented?
I'm having issues when trying to unmask a value.

i've tried
``` javascript
VMasker.unMask("(01) 1111-1919", "(99) 9999-9999");

VMasker(this.state.value).unMask("(99) 9999-9999");

VMasker(this.state.value).maskPattern("(99) 9999-9999");
VMasker(this.state.value).unMask();
```

and none of these works :(

**Comment by fernandofleury** [comment]
@dmscn-six this is lib is not being maintained anymore. Please use something like: https://github.com/text-mask/text-mask
