### ISSUE TITLE
Unable to clone repo in windows due to colon character in 'bankfacil:vanilla-masker' folder

### ISSUE THREAD

**Issue by yor-so** [vanilla-masker/vanilla-masker#151]
The repository can't be cloned in Windows because there's a colon in the 'bankfacil:vanilla-masker' folder.

**Comment by LeonardoCamargo31** [comment]
This repository is dead, what is the possibility of cloning it and making these improvements?

**Comment by yor-so** [comment]
@LeonardoCamargo31 I did exactly that, you can check here:
https://github.com/yor-so/vanilla-masker

I removed that file so the repo can be cloned in windows now.
Plus, I fixed an issue with the masker not masking the input if data is added with a right click - > copy.
