### ISSUE TITLE
Allow MaskMoney to be used with any value

### ISSUE THREAD

**Issue by hugooliveirad** [vanilla-masker/vanilla-masker#2]
MoneyMask would be far useful if it could be used in any property in any element.

Some times we would want to apply a money mask in other elements, such as `span` and `label` (e.g. http://bradfrostweb.com/blog/post/labelmask/)

This will be specially useful if we create an AMD version of MaskMoney (#1)

**Comment by g-guth** [comment]
is this function yet available? I couldnt use it.
