### ISSUE TITLE
Missing support for negative values

### ISSUE THREAD

**Issue by pomek** [vanilla-masker/vanilla-masker#33]
Hi,

Maybe it's not a bug... How can I setup mask for numbers with negative values?

**Comment by leandroadacosta** [comment]
Hi @pomek, welcome :)
Right, it's not a bug, we can implement it. Any suggestions? @caio-ribeiro-pereira?

**Comment by caio-ribeiro-pereira** [comment]
Well to mask numbers you can use maskNumber() with positive and negative
values, take a look:
https://github.com/BankFacil/vanilla-masker#only-numbers

Only maskMoney doesn't support yet.

2015-03-16 12:23 GMT-03:00 Leandro Alvares da Costa <
notifications@github.com>:

> Hi @pomek <https://github.com/pomek>, welcome :)
> Right, it's not a bug, we can implement it. Any suggestions?
> @caio-ribeiro-pereira <https://github.com/caio-ribeiro-pereira>?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BankFacil/vanilla-masker/issues/33#issuecomment-81733306>
> .
>



-- 
Att,
Caio Ribeiro Pereira
Web Developer
Blog: http://udgwebdev.com
LinkedIn: http://br.linkedin.com/pub/caio-ribeiro-pereira/25/7ba/465
Twitter: http://twitter.com/crp_underground
Github: https://github.com/caio-ribeiro-pereira

**Comment by pomek** [comment]
Hi,

I would like to create mask on float numbers with negative values. I tried use: `VMasket(element). maskPattern("-?99,9")`, but it isn't a good idea because it doesn't work :<

Any idea guys?

**Comment by rmonteiro89** [comment]
Hi, @pomek I didn't understand what you wanted to do, but I tried something like that:
```
VMasker.toPattern(375, "-99,9");
"-37,5"
```

Is something close to it?

**Comment by pomek** [comment]
Hi,

It doesn't work correctly for me, because I expected that if I get the positive number, mask returns positive number. If I get the negative number, mask returns negative number.

By the way, I guess I could check if I get the positive or negative number and choose particular pattern.

I close this issue, because it is already out of date.

**Comment by rmonteiro89** [comment]
Hi @pomek ,

I got what you said, because of that I deleted my comment.

We think it makes sense, so we are trying to do something like if you use VMasker.toMoney(-375), it will return "-3,75".

I am re-opening this issue until we fix it, okay? Tks.

**Comment by pomek** [comment]
Ok, txx

**Comment by leandroadacosta** [comment]
Hi @pomek :) We should implement this issue at VM next version.

**Comment by fernandofleury** [comment]
fixed.
