### ISSUE TITLE
Shouldn't the eventListeners for the input be used with attachEvent and addEventListener?

### ISSUE THREAD

**Issue by fernandofleury** [vanilla-masker/vanilla-masker#38]
Greetings!

This is my first time using the VMasker, though I've been watching the project for a while.

In this particular project of mine I need to support IE8, so I've opted to use onkeyup instead of a "addEvent" function in order to keep it simple.

Shouldn't the concern of working with non-overriding listeners such as attachEvent/addEventListener of the third party lib (In this case VMasker)?

I will change my listeners to "addEvent" in this scenario, cause I really need a mask lib. But I've got my mind around this and decided to ask it.

**Comment by leandroadacosta** [comment]
@fernandofleury we are trying to solve it. We will use addEvent and attachEvent as fallback. What do you think? Sorry for our delay.

**Comment by fernandofleury** [comment]
Well, now I think it's time for me to apologize for the delay. I see a couple ways to work with this.

But the easiest one is by far with addEvent/attachEvent as the main handler. Close to no side effects. How is it going? Did you guys change it?

**Comment by fernandofleury** [comment]
happy birthday to this issue 🎂
